### ISSUE TITLE
Сделать сноски на страницах /book и /lb/rb/chid.

### ISSUE THREAD

**Issue by stakap** [stakap/lib-view#41]
Сноски должны быть отсортированы по возрастанию id. 
Должны быть видны с/без аутентификации.

**Comment by NewbieWin** [comment]
Отчет о тестировании:
-Сноски книги отображаются по возрастанию 
-Нумерация сносок соответствует id в БД
-Сноси и их нумерация видна с/без аутентификации

Основной функционал работает:

Новый пользователь регистрируется и логинится
Новые Автор\книга\метакнига добавляются
Текст книги и сноски добавляются
Новая книга отображается на главной странице
Параллельное чтение работает
Кнопки “Next chapter" и “Previous chapter” отображаются и работают
Токен пользователя отображается
Книга  с корректным названием  приходит на почту указанную при регистрации
В лк отображается наличие или отсутствие текста в книги
Из личного кабинета можно удалить свою книгу

**Comment by NewbieWin** [comment]
Отчет о тестировании:
-Сноски книги отображаются по возрастанию
-Нумерация сносок соответствует id в БД
-Сноси и их нумерация видна с/без аутентификации в режиме "одинарного" чтения
-В параллельном чтении сносок нет

Описание ошибки:
При нажатии кнопки "bilingual"  открывается книга в параллельном чтении ( на одном языке)
Внизу страницы сразу же отображаются все сноски из книги ( не только 1й главы)
При смене языка сноски пропадают, в конце книг сносок нет.


Основной функционал работает:

Новый пользователь регистрируется и логинится
Новые Автор\книга\метакнига добавляются
Текст книги и сноски добавляются
Новая книга отображается на главной странице
Параллельное чтение работает
Кнопки “Next chapter" и “Previous chapter” отображаются и работают
Токен пользователя отображается
Книга с корректным названием приходит на почту указанную при регистрации
В лк отображается наличие или отсутствие текста в книги
Из личного кабинета можно удалить свою книгу

**Comment by GithubAgitator** [comment]
Отчет о тестировании:
1. При билингвальгом чтении сноски все отображаются после первой главы
![image](https://github.com/stakap/lib-view/assets/103563978/91537cf9-2072-4b2d-a5a5-ea1810e1a4c0)

2. При смене языка при билингварном чтении сноски вообще не отображаются
3. В БД в таблицу notes (chapters = 0)
4. Если в БД изменить chapters (проставить номер главы) то сноски отображаются после каждой главы
5. При обычном чтении сноски отображаются после всех глав (в конце)
6. Остальной функционал работает
