### ISSUE TITLE
Сделать сноски в монолингвальном и билингвальном пдф

### ISSUE THREAD

**Issue by stakap** [stakap/lib-view#44]

**Comment by Zakanya** [comment]
Отчет - 28-pdf-notes
•	У авторизованного пользователя, при билингвальном и монолингвальный чтении книг, имеется кнопка «Download»
•	Кнопка «Download» работает, 
•	При скачивании книги в билингвальном, монолингвальном  режиме файл PDF скачивается на ПК, а так же отправляется  на почту.
•	Сноски находятся в конце книги.
•	Если не изменить язык книги, то файл скачивается с книгами на одинаковом языке.

**Comment by GithubAgitator** [comment]
Отчет о тестировании 28-pdf-notes:
Книги скачиваются в pdf формате (локально и приходят на почту)
Значение сносок отображаются в конце книги
Другой функционал работает

**Comment by EvgenMarkello** [comment]
Отчет 28-pdf-notes (v.0.2.0)
Основной функционал работает
Багов нет.

Предложения:
-Пояснения к сноскам сделать в конце глав
-Название скачанной билингвальной книги ( согласовать с аналитиками)
